# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66fb9920db262e15679421bdcefc6c7aaa5f75243ba5fd811434b3f2e39d4f3aa62110fa443b58924f44ccdafaf23dd39f21e5157ee4d85074e35d4d907a2e14

test:
  secret_key_base: 647112ff0d7945bed27ee34038771f30d4741d9abd1cae3a9511f59be7d59b7fd7399d9b908d841a1b0ebb58300b26994bce39120effb1424804b0b48d304089

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
